//
//  UniversityNames.swift
//  ALUM
//
//  Created by Neelam Gurnani on 3/7/23.
//

import Foundation

class UniversityNames {
    static var universityNames: [String] =
        [
            "University of California - Merced",
            "University of California - Riverside",
            "University of California - San Francisco",
            "Harvard University",
            "Massachusetts Institute of Technology",
            "Stanford University",
            "California Institute of Technology",
            "Columbia University",
            "Princeton University",
            "University of Chicago",
            "Yale University",
            "Cornell University",
            "Johns Hopkins University",
            "University of Pennsylvania",
            "Duke University",
            "Northwestern University",
            "University of California - Berkeley",
            "University of Michigan - Ann Arbor",
            "University of California - Los Angeles",
            "University of Virginia",
            "Carnegie Mellon University",
            "Georgia Institute of Technology",
            "University of North Carolina - Chapel Hill",
            "University of California - San Diego",
            "University of Wisconsin - Madison",
            "University of Illinois - Urbana-Champaign",
            "University of Washington",
            "University of Texas - Austin",
            "University of Southern California",
            "University of California - Davis",
            "University of California - Santa Barbara",
            "New York University",
            "Brown University",
            "University of Minnesota - Twin Cities",
            "University of Pittsburgh",
            "Emory University",
            "University of California - Irvine",
            "University of Maryland - College Park",
            "Ohio State University - Columbus",
            "Pennsylvania State University - University Park",
            "University of Colorado - Boulder",
            "Purdue University - West Lafayette",
            "University of Arizona",
            "University of Notre Dame",
            "University of Rochester",
            "University of Utah",
            "University of Massachusetts - Amherst",
            "University of Miami",
            "Boston College",
            "Rice University",
            "University of Iowa",
            "University of Oregon",
            "University of Delaware",
            "Indiana University - Bloomington",
            "Michigan State University",
            "Texas A&M University - College Station",
            "Tufts University",
            "University of California - Santa Cruz",
            "University of Florida",
            "University of Georgia",
            "University of Kentucky",
            "University of New Mexico",
            "University of Oklahoma",
            "University of Tennessee",
            "Arizona State University - Tempe",
            "Case Western Reserve University",
            "Clemson University",
            "Iowa State University",
            "Lehigh University",
            "North Carolina State University - Raleigh",
            "Rensselaer Polytechnic Institute",
            "University at Buffalo - SUNY",
            "University of Alabama",
            "University of Connecticut",
            "University of Denver",
            "University of Houston",
            "University of Kansas",
            "University of Nebraska - Lincoln",
            "University of South Carolina",
            "University of Vermont",
            "George Washington University",
            "Oregon State University",
            "Southern Methodist University",
            "Syracuse University",
            "Temple University",
            "University of Cincinnati",
            "University of Hawaii - Manoa",
            "University of Missouri",
            "University of Nebraska Medical Center",
            "University of Nevada - Las Vegas",
            "University of Nevada - Reno",
            "University of North Dakota",
            "University of South Florida",
            "University of Toledo",
            "University of Tulsa",
            "University of Wyoming"
        ]
}
