import { Inter } from 'next/font/google';

import '@/styles/globals.css'
import styles from '@/styles/RootLayout.module.css';
import { Sidebar } from '@/components/sidebar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={styles.rootHtml}>
      <body className={`${inter.className} ${styles.mainContainer}`}>
        <Sidebar />
        <div className={styles.content}>
          {children}
        </div>
      </body>
    </html>
  )
}
