name: Backend - lint and style checks

on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**
      - .github/workflows/lint-check.yml

jobs:
  backend:
    name: Backend lint and style check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - working-directory: backend # Change this to the name of your backend directory
      run: |
        npm ci
        npm run lint-check