name: iOS Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 13

    - name: Build and test
      run: xcodebuild build -workspace ALUM/ALUM.xcodeproj/project.xcworkspace -scheme ALUM -destination "platform=iOS Simulator,name=iPhone 11 Pro" 
